name: Metrics

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@v3.33

        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Perfil
          user: Bernard2806

          # Apariencia
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires
          config_twemoji: yes

          # Calendario
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Lenguajes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github

          # Líneas de código
          plugin_lines: yes
          plugin_lines_sections: base

          # Salida
          filename: github-metrics.svg
